feat: variant option
sajari/sdk-react pull request #514
Opened 2021-06-09 03:46 UTC by tuanddd

2021-06-11 04:46 UTC, zlatanpham commented on packages/hooks/src/ContextProvider/types.ts
> +  variantImageIds?: string[];
I'm wondering why it's not just one field to hold a list of images? For examples:
```suggestion
 images?: string[];
```

2021-06-15 03:12 UTC, tuanddd commented on packages/hooks/src/ContextProvider/types.ts
> +  variantImageIds?: string[];
All 3 have different values and meaning, in order to get the right variant images please [see this](https://sajari.atlassian.net/wiki/spaces/SAJARI/pages/1209991336/Search+Result+Settings?focusedCommentId=1283096679#comment-1283096679)

2021-06-15 08:00 UTC, zlatanpham commented on packages/hooks/src/ContextProvider/types.ts
> +  variantImageIds?: string[];
If so, I think we are opinionating Shopify settings here. Ideally, the component should know nothing regarding Shopify and render the images based on a single prop. We can compute the value of the prop via the [mapResultsField](https://github.com/sajari/sdk-react/blob/master/packages/search-ui/src/utils/mapResultFields.ts#L40), don't we?

2021-06-15 08:28 UTC, tuanddd commented on packages/hooks/src/ContextProvider/types.ts
> +  variantImageIds?: string[];
You are correct, I'll make the changes.

2021-06-16 06:10 UTC, zlatanpham requested changes
@tuanddd I've left some suggestions. Furthermore, I don't see a change of the docs in the PR, can you make the update?

2021-06-16 06:10 UTC, zlatanpham commented on packages/search-ui/src/Results/components/Result/index.tsx
> +                      <Image src={url} aspectRatio={1} objectFit="cover" objectPosition="top" />
Often, it's helpful to support `alt` for the thumbnail pattern. Should we consider adding it?

2021-06-16 06:10 UTC, zlatanpham commented on packages/search-ui/src/Results/components/Result/index.tsx
> +                        onMouseEnter={() => {
I don't see from the code that it supports keyboard accessibility. Can we have the support?

2021-06-16 07:28 UTC, tuanddd commented on packages/search-ui/src/Results/components/Result/index.tsx
> +                      <Image src={url} aspectRatio={1} objectFit="cover" objectPosition="top" />
Instead of adding `alt` to the image, I added `role=img` and `aria-label` to the container.

2021-06-16 09:29 UTC, zlatanpham reviewed
@tuanddd can we have an example in the docs for the change? Additionally, this section looks broken which might be caused by the change.

![image](https://user-images.githubusercontent.com/12707960/122194738-e8846c00-cebf-11eb-98a4-b34a8c880b2c.png)

2021-06-16 09:33 UTC, zlatanpham commented on packages/search-ui/src/Results/components/Result/index.tsx
> +        <Box css={styles.previewImagesContainer} aria-label={`${decodeHTML(title)}'s images`}>
Can we do translation here?

2021-06-16 09:33 UTC, zlatanpham commented on packages/search-ui/src/Results/components/Result/index.tsx
> +                  aria-label={`${decodeHTML(title)} image number ${i + 1}`}
Same question with translation.

2021-06-21 08:41 UTC, zlatanpham approved these changes
I've left 2 more suggestions, see if you think they need to be updated. Otherwise, it looks good to merge.

2021-06-21 08:41 UTC, zlatanpham commented on packages/components/src/Image/styles.ts
> +      return tw`object-center`;
```suggestion
    default:
      return tw`object-center`;
```

2021-06-21 08:41 UTC, zlatanpham commented on packages/search-ui/src/Results/components/Result/index.tsx
> +            image.map((url, i) => {
Shoud `isArray` be enough for the case?

```suggestion
          {isArray(image) &&
            image.map((url, i) => {
```

2021-06-21 08:54 UTC, zlatanpham approved these changes

2021-06-21 09:04 UTC, merged