feat: add support for product statuses and price
sajari/sdk-react pull request #597
Opened 2021-08-18 11:20 UTC by tuanddd

When changing to use result template, we need to keep the following existing features that is offered out-of-the-box when using the `Result` component:
- [x] Ability to render statuses (new arrival, on sale, out of stock) -> extracted to `useProductStatuses` common hook
- [x] Ability to render price (sale price, original price) -> extracted to `useRenderPrice` common hook
- [x] Internationalization -> pass the localized text to the result template for further use
- [ ] Ability to change image on hover -> The plan is to use DOM manipulation to add hover logic to an `img` element (perhaps use something like `data-sj-second-image` attribute to hold the second image url)
- [ ] Ability to show product variant images -> DOM manipulation
- [ ] Tracking logic -> `ClickTracking` should be easy to do, not sure about `PosNegTracking`

2021-09-01 06:42 UTC, tuanddd commented
Ready for review.

2021-09-02 02:23 UTC, wwalser requested changes
Unfortunately I've found an architectural note that I think is substantial.

Sorry about the additional effort, but I think we should consider moving the tracking data manipulation back into Result and duplicate it inside of TemplateResult. I'm happy to hear your ideas.

2021-09-02 02:23 UTC, wwalser commented on packages/search-ui/src/Results/index.tsx
> +      const { href, onClick: clickTrackingOnClick } = useClickTracking({
These calls to useClickTracking and usePosNegTracking are violations of the [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html) and can cause problems if subsequent authors fail to understand how they are used.

There are two options for cases like this:
1. If these hooks don't actually contain the use of any built-in react hooks such as useMemo or useState, then they can simply be renamed so that it's obvious that they are not _actually_ hooks.
2. If they are actually hooks and call order matters, then we need to find a way to move them to the top level of some React component. The simplest way would be to write a wrapper component for Result and TemplateResult that calls these for each result items.

My reading of useClickTracking and usePosNegTracking is that they aren't actually hooks (they don't use any built-in React hooks and call order doesn't matter) so we can simply rename the functions to make it clear that they are simple data manipulation utilities.

2021-09-02 02:23 UTC, wwalser commented on packages/search-ui/src/Results/index.tsx
> +    return untrackedResults?.map((data) => {
This introduced another loop over the results. Perhaps it would be better to have this tracking data management inside both <Result and <TemplateResult ?

Given that we paginate an additional loop isn't the end of the world but given the note below, I do wonder if this extra loop is an antipattern.

2021-09-06 02:43 UTC, tuanddd commented
Sorry accidentally hit the request review button, this is not ready yet.

2021-09-08 04:31 UTC, wwalser approved these changes
Looks good. You may want additional version bumps in the changeset but that's up to you. One other comment that is up to your discretion as well.

2021-09-08 04:31 UTC, wwalser commented on .changeset/rotten-candles-attack.md
> +'@sajari/react-sdk-utils': minor
utils is used in most of the other libraries so you may need to bump those as well in order to get the changes distributed everywhere?

2021-09-08 04:31 UTC, wwalser commented on packages/search-ui/src/Results/useHoverImage.ts
> +export function useHoverImage(props: Props) {
Mind explicitly defining the export type so that it's clear to readers without having to inspect with typescript or read the code?

2021-09-08 06:31 UTC, zlatanpham approved these changes

2021-09-08 06:52 UTC, merged