feat: add banner replacement
sajari/sdk-react pull request #729
Opened 2022-01-19 15:35 UTC by zlatanpham

2022-02-07 14:41 UTC, zlatanpham commented on packages/search-ui/src/Results/components/BannerItem/index.tsx
> +    }, 0);
@tuanddd spent some time playing with different cases and found one case the banners still overlap. Maybe you should take a look to update the logic? Also, the computation looks a bit complicated here. By any chance, it can be simplified? or covered by a test?

```
[
    {
        "id": "0",
        "position": 1,
        "width": 2,
        "height": 2,
        "imageUrl": "https://ik.imagekit.io/j7pm1g0d0uh/staging/1617855295958267636/sajari-thanh-pham/24K9t7bKfr0iexgRkYu98prYwWQ",
        "targetUrl": "https://example.com",
        "title": "Search text",
        "description": "Hello world",
        "textColor": "#000000",
        "textPosition": "TEXT_POSITION_TOP_LEFT"
    },
    {
        "id": "1",
        "position": 4,
        "width": 1,
        "height": 1,
        "imageUrl": "https://ik.imagekit.io/j7pm1g0d0uh/staging/1617855295958267636/sajari-thanh-pham/24K9t8NXkOJWSELIrGkKJZfbziU",
        "targetUrl": "https://example.com",
        "textPosition": "TEXT_POSITION_TOP_LEFT"
    }
]
```

2022-02-11 01:45 UTC, wwalser requested changes
Would like to demo this in showcase today. If you have a chance to get the changes done, great, if not I will demo from this branch.

2022-02-11 01:45 UTC, wwalser commented on packages/search-ui/src/Results/index.tsx
> +      return (results ?? []).map(() => undefined);
I don't think this is necessary. The lookup for a banner in each place that pulls from this array should expect that the item at any location in the array is either a banner or undefined — so they all need to check for undefined.

`return [];` should work?

edit: The same thinking applies here w/ an indexed map, as `bannerByPosition[n]` would also return undefined when zero banners exist.

2022-02-11 01:45 UTC, wwalser commented on packages/search-ui/src/Results/styles.ts
> +export function getNumberOfCols({ columns, columnMinWidth = 240, width }: Props) {
Add a comment explaining what this function returns. Not a huge deal but it's proximity to banners code initially lead me to believe it had to do with the width of a banner.

2022-02-11 01:45 UTC, wwalser commented on packages/search-ui/src/Results/index.tsx
> +  const bannersExpanded = React.useMemo(() => {
I I think the rewrite to `bannersByPosition` eliminates the need for this sparse array?

We would already have a data structure that gives us an easy way lookup banners by their position in the results-by-page.

2022-02-11 03:12 UTC, wwalser commented
I believe this change may also need to pull in the latest version of sdk-js?

2022-02-11 03:53 UTC, zlatanpham commented
> I believe this change may also need to pull in the latest version of sdk-js?

@wwalser we've already upgraded the version in https://github.com/sajari/sdk-react/pull/731

2022-02-11 04:02 UTC, wwalser commented
My fault. I was trying to test this code in search-widgets using yalc and had forgotten that I also need to run `yarn install` after a `yalc add` to pull in transitive deps.

2022-02-11 05:06 UTC, wwalser requested changes

2022-02-11 05:11 UTC, zlatanpham commented on packages/search-ui/src/Results/index.tsx
> +    allowBanners = false,
Done

2022-02-11 05:12 UTC, zlatanpham commented
@wwalser I've updated the code as your feedback. Can you take a look?

2022-02-11 05:52 UTC, wwalser submitted a review, later dismissed
One question, just to confirm. Then free to land.

2022-02-12 04:57 UTC, wwalser commented on packages/search-ui/src/Results/index.tsx
> +    appearance !== 'grid' || !checkValidResultTemplate(resultTemplate) || !allowBanners
I think this still empties the banners in the case that no resultTemplate is provided. Why do we need to check `resultTemplate` here at all?

2022-02-13 23:21 UTC, wwalser approved these changes

2022-02-13 23:21 UTC, merged