fix: performance issue on results
sajari/sdk-react pull request #758
Opened 2022-03-11 10:48 UTC by chidojiro

2022-03-14 14:36 UTC, zlatanpham reviewed
This code looks good to me but it's not quite clear how different the performance is after the change. Can we have a before/after comparison or performance profiling evidence for the update?

2022-03-14 14:36 UTC, zlatanpham commented on packages/hooks/CHANGELOG.md
> +  pipeline.listen('result-clicked', (url) => {
I know it's just Eslint stuff but this change is not supposed to be included in the PR.

2022-03-14 15:04 UTC, wwalser requested changes

2022-03-14 15:04 UTC, wwalser commented on packages/search-ui/src/Results/index.tsx
> +  const { currency, tracking, ratingMax, language } = useSearchUIContext();
Is this the only substantial change, moving the context hook up the tree?

2022-03-15 23:53 UTC, wwalser submitted a review, later dismissed

2022-03-17 11:41 UTC, zlatanpham approved these changes

2022-03-17 11:55 UTC, zlatanpham commented
One note is that we are using `JSON.stringify` comparison in [result component](https://github.com/sajari/sdk-react/blob/52ef27ef4c83d769ebc841a856591af887d4b140/packages/search-ui/src/Results/components/Result/index.tsx#L331). This check looks expensive and I'm wondering if we can have an equivalent check by `_id`?

2022-03-18 00:02 UTC, zlatanpham commented
> One note is that we are using `JSON.stringify` comparison in [result component](https://github.com/sajari/sdk-react/blob/52ef27ef4c83d769ebc841a856591af887d4b140/packages/search-ui/src/Results/components/Result/index.tsx#L331). This check looks expensive and I'm wondering if we can have an equivalent check by `_id`?

@wwalser just reminded me of one issue that makes my previous assumption incorrect:

> I think the problem with _id in sdk-react is that _id may not always be returned in search queries. It is returned by default, but customers can change the default result fields of their pipeline.

So we are good without touching the part for now.

2022-03-18 05:12 UTC, wwalser commented
Rebase on master then feel free to pull the trigger. Thanks @chidojiro

2022-03-22 09:19 UTC, zlatanpham approved these changes

2022-03-22 09:30 UTC, merged