fix: upgrade downshift and remove breaking changes
sajari/sdk-react pull request #858
Opened 2022-11-08 23:31 UTC by beatrice94

Upgraded Downshift from 6.1.0 -> 7.0.1
Removed references to GetComboboxProps

2022-11-09 00:57 UTC, jkaho requested changes

2022-11-09 00:57 UTC, jkaho commented on package.json
> +  }
I think you can remove this `yalc` dependency. I assume it was added when you were trying to install it globally
```suggestion
```

2022-11-09 00:57 UTC, jkaho commented on packages/components/package.json
> +    "yalc": "^1.0.0-pre.53"
You can remove this too
```suggestion
```

2022-11-09 00:57 UTC, jkaho commented on packages/components/src/Select/index.tsx
> +      case useSelect.stateChangeTypes.ToggleButtonKeyDownEnter:
What does this change do?

2022-11-09 00:57 UTC, jkaho commented on yarn.lock
> -"compute-scroll-into-view@npm:^1.0.16":
Was this supposed to be deleted?

2022-11-09 02:28 UTC, beatrice94 commented on packages/components/src/Select/index.tsx
> +      case useSelect.stateChangeTypes.ToggleButtonKeyDownEnter:
This change is because the name of the properties were changed. This can be found in the migration documents [here](https://github.com/downshift-js/downshift/blob/master/src/hooks/MIGRATION_V7.md)

2022-11-09 02:29 UTC, beatrice94 commented on yarn.lock
> -"compute-scroll-into-view@npm:^1.0.16":
Oh this was no meant to be deleted, will update

2022-11-09 02:36 UTC, beatrice94 commented on yarn.lock
> -"compute-scroll-into-view@npm:^1.0.16":
It looks like this was replaced when running yarn

2022-11-09 02:37 UTC, jkaho commented on yarn.lock
> -"compute-scroll-into-view@npm:^1.0.16":
As discussed, this is fine

2022-11-09 02:45 UTC, beatrice94 reviewed
Made requested changes to package files

2022-11-09 06:09 UTC, jkaho commented
It looks like the size and position of the combobox text has changed.

**Before**
<img width="796" alt="Screen Shot 2022-11-09 at 5 06 57 pm" src="https://user-images.githubusercontent.com/72959522/200752631-7df75835-9050-43d7-8448-ecefaa37d359.png">

**After**
<img width="801" alt="Screen Shot 2022-11-09 at 5 06 52 pm" src="https://user-images.githubusercontent.com/72959522/200752645-bfb16da9-c540-4986-ad1d-45e030d78941.png">

Hopefully it's an easy fix!

2022-11-10 02:45 UTC, wwalser approved these changes
The styling change is a good catch. Once that's fixed, feel free to pull the trigger with this.

Nice upgrade @beatrice94

2022-11-10 02:46 UTC, wwalser commented
I've changed some configuration on the Netlify builds. I believe those should pass once you push another commit.

2022-11-14 04:33 UTC, jkaho requested changes
Small nit!

2022-11-14 04:33 UTC, jkaho commented on packages/components/src/Combobox/styles.ts
> +      return tw`pl-10 text-base`;
I think leaving the padding at 9 should be fine
```suggestion
      return tw`pl-9 text-base`;
```

![Screen Shot 2022-11-14 at 3 20 52 pm](https://user-images.githubusercontent.com/72959522/201574797-18f83571-1738-4da2-9cf0-f51d0bca8724.png)

2022-11-14 04:40 UTC, jkaho requested changes

2022-11-14 04:40 UTC, jkaho commented on .changeset/healthy-books-own.md
> +'@sajari/react-components': major
I've checked in with Wes, who thinks this should be a minor bump

2022-11-14 05:38 UTC, jkaho approved these changes

2022-11-14 05:51 UTC, merged