feat: lowercase search input value when looking for redirects
sajari/sdk-react pull request #875
Opened 2023-02-07 03:15 UTC by jkaho

Assume users don't care about the letter case of a query string for redirects and lowercase all inputs when retrieving redirects.

[DAU-249](https://algolia.atlassian.net/browse/DAU-249)

2023-02-07 03:39 UTC, jonathaningram requested changes

2023-02-07 03:39 UTC, jonathaningram commented on packages/search-ui/src/Input/index.tsx
> +          const redirectValue = redirectsRef.current[value.toLowerCase()];
I think this only works if the items in `redirectsRef.current` are also lowercased, no?

E.g. if the redirect is `Tires`, this never triggers if the user types `Tires` does it?

2023-02-07 03:52 UTC, jkaho commented on packages/search-ui/src/Input/index.tsx
> +          const redirectValue = redirectsRef.current[value.toLowerCase()];
Yeah, this assumes that their redirects are all lowercased. I would think we might want to build in some kind of case-sensitivity feature into the backend where the user can decide whether their redirect is case-sensitive or not upon creation? But yes you're right, if they have a redirect with capitals, then there will be no way to trigger it.

My concern with lowercasing the whole redirects object was that it could be a lot of work if the user has a lot of redirects, since we'd do it each time the search response is returned. But maybe it's safe to assume that they wouldn't have that many. WDYT?

2023-02-07 04:00 UTC, jonathaningram commented on packages/search-ui/src/Input/index.tsx
> +          const redirectValue = redirectsRef.current[value.toLowerCase()];
Yeah I don't think iterating over those objects in the response and transforming the keys to lowercase is that expensive.

2023-02-07 04:01 UTC, jonathaningram commented on packages/search-ui/src/Input/index.tsx
> +          const redirectValue = redirectsRef.current[value.toLowerCase()];
If we change the behavior such that looking up `Tires` in there no longer works, that breaks for every client using this which isn't already lowercasing. So we should ensure we lowercase the redirects coming from the backend response plus the input value.

2023-02-07 04:03 UTC, jonathaningram requested changes
RCFV

2023-02-07 05:51 UTC, jonathaningram requested changes

2023-02-07 05:51 UTC, jonathaningram commented on packages/search-ui/src/Input/utils/index.test.ts
> +    Test: { id: '4', target: 'd' },
Should you add a duplicate here e.g. `test` to prove that only one survives?

2023-02-07 05:51 UTC, jonathaningram commented on packages/search-ui/src/Input/index.test.tsx
>            sheets: redirectTarget,
To prove that the test works, should we not have the server respond with, say,  a `Sheets2` redirect as well?

2023-02-07 06:23 UTC, jkaho commented on packages/search-ui/src/Input/utils/index.test.ts
> +    Test: { id: '4', target: 'd' },
Right, good point. So we essentially don't support users having different redirects with the same names and different casing because we drop all except the last in the object. Not that I can see anyone doing that, but maybe it's worth mentioning this in the docs?

2023-02-07 06:25 UTC, jonathaningram commented on packages/search-ui/src/Input/utils/index.test.ts
> +    Test: { id: '4', target: 'd' },
Yep or whatever order Object.keys returns its keys.

Worth adding to the docs.

2023-02-07 22:16 UTC, jonathaningram requested changes
Small doc nits. Good to go otherwise.

2023-02-07 22:16 UTC, jonathaningram commented on docs/pages/search-ui/input.mdx
> +The component does not support the handling of multiple redirects for queries of the same word with varied letter casing. For example, if you have created redirects for each of the queries `computer`
```suggestion
The component does not support the handling of multiple redirects for queries of the same word with varied letter casing. For example, if you have created redirects for each of the queries `computer`, `Computer`, and `COMPUTER`, only one of them is used (dependent upon your browser).
```

2023-02-07 22:16 UTC, jonathaningram commented on docs/pages/search-ui/input.mdx
> +The `Input` component treats redirects as _case-insensitive_, meaning the user-inputted value `Computer` will return the redirect for the query `computer` and vice versa.
```suggestion
The `Input` component treats redirects as _case-insensitive_, meaning the user-inputted value `Computer` returns the redirect for the query `computer` and vice versa.
```

2023-02-08 00:36 UTC, jonathaningram submitted a review, later dismissed

2023-02-08 01:47 UTC, jkaho commented
@jonathaningram sorry needed to rejig the test since it was passing locally but failing in the CI check

2023-02-08 02:33 UTC, jonathaningram approved these changes

2023-02-08 02:38 UTC, merged